/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Caneta c = new Caneta();

        c.setCor("verde");
        System.out.println(c.desenhar());
    }
}
